### ISSUE TITLE
How to run this project

### ISSUE THREAD

**Issue by rishitgupta1808** [viesa/AStarVisualization#2]
Please provide me a step to step guide about how to run this project.

**Comment by saffronjam** [comment]
What operating system are you using? 
There is a short instruction in the Readme, and it really is super easy! No external library to install yourself. Just build project and start directly.

- Windows
Use Visual Studio 2019 
![image](https://user-images.githubusercontent.com/26722370/105551689-404ceb80-5d03-11eb-846f-db2862ca64d0.png)
Then just run Client (screenshot of this in Readme)

- Linux
Use either CLion or Visual Studio Code (using CMake tool plugin).
![image](https://user-images.githubusercontent.com/26722370/105552301-03cdbf80-5d04-11eb-9856-349404897093.png)
Then just run Client (screenshots of this in Readme)

- Mac
The project is not supported for Mac OS!


Would you prefer to have a prebuilt executable for the application?
